-- Active: 1691416914754@@127.0.0.1@3306@base_de_dados
ALTER TABLE users ADD created_at DATETIME DEFAULT NOW() NOT NULL;

ALTER TABLE users ADD updated_at DATETIME DEFAULT NOW() ON UPDATE NOW() NOT NULL;

ALTER TABLE users_roles ADD created_at DATETIME DEFAULT NOW() NOT NULL;

ALTER TABLE users_roles ADD updated_at DATETIME DEFAULT NOW() ON UPDATE NOW() NOT NULL;